.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH Quadrapassel 6 "2007\-06\-09" "GNOME"
.SH NAME
Quadrapassel \- Tetris-like game for GNOME
.SH SYNOPSIS
.B quadrapassel
.RI [ OPTION... ]
.SH DESCRIPTION
Quadrapassel comes from the classic falling-block game, Tetris. The goal
of the game is to create complete horizontal lines of blocks, which
will disappear. 
.SH OPTIONS
.TP
.B \-l, \-\-level=LEVEL
Set starting level (1 or greater)
.P
This program also accepts the standard GNOME and GTK options.
.SH AUTHORS
.B quadrapassel
was written by J. Marcin Gorycki <janusz.gorycki@intel.com>.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR "gtk-options" (7),
.BR "gnome-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
