name: quadrapassel
version: git
adopt-info: quadrapassel

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  quadrapassel:
    interface: dbus
    bus: session
    name: org.gnome.Quadrapassel

apps:
  quadrapassel:
    command: usr/bin/quadrapassel
    extensions: [gnome-3-38]
    plugs:
      - gsettings
      - opengl
      - audio-playback
    desktop: usr/share/applications/org.gnome.Quadrapassel.desktop
    common-id: org.gnome.Quadrapassel.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/quadrapassel

parts:
# needed for clutter to work
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib

  quadrapassel:
    after: [snapcraft-preload]
    source: .
    source-type: git
    plugin: meson
    # workaround the issue described in https://launchpad.net/bugs/1583250
    meson-parameters: [--prefix=/snap/quadrapassel/current/usr]
    parse-info: [usr/share/metainfo/org.gnome.Quadrapassel.metainfo.xml]
    organize:
      snap/quadrapassel/current/usr: usr
    override-build: |
      sed -i.bak -e 's|=org.gnome.Quadrapassel$|=${SNAP}/meta/gui/org.gnome.Quadrapassel.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Quadrapassel.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Quadrapassel.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/quadrapassel/current/usr/share/applications/org.gnome.Quadrapassel.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - libmanette-0.2-dev

  libraries:
    plugin: nil
    stage-packages:
      - libmanette-0.2-0
    prime:
      - usr/lib/*/libmanette*
