name: quadrapassel
version: git
summary: Fit falling blocks together
description: |
  Quadrapassel is a derivative of a classic Russian falling-block game.
  Reposition and rotate the blocks as they fall, and attempt to fit them
  together. When you form a complete horizontal row of blocks, the row will
  disappear and you score points. The game is over when the blocks get stacked
  too high. As your score gets higher, you level up and the blocks fall faster.

  If you're looking for a challenge, Quadrapassel allows you to increase the
  initial speed of the blocks, or begin the game with partial blocks on some
  of the rows. Or, instead of allowing the blocks to fall randomly, it can
  select blocks that will be hard for you to place.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  quadrapassel:
    interface: dbus
    bus: session
    name: org.gnome.Quadrapassel

apps:
  quadrapassel:
    command: desktop-launch quadrapassel
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - pulseaudio
      - unity7
      - wayland
    desktop: usr/share/applications/or.gnome.Quadrapassel.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/quadrapassel

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  libcanberra:
    source: git://git.0pointer.de/libcanberra
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/snap/quadrapassel/current/usr
      - --enable-pulse
      - --enable-gstreamer
      - --enable-gtk3
      - --enable-alsa
      - --disable-oss
    organize:
      snap/quadrapassel/current/usr: usr
    build-packages:
      - libltdl-dev
      - libasound2-dev
      - libvorbis-dev
      - libgtk-3-dev
      - libtdb-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - gtk-doc-tools

  gsound:
    after: [libcanberra]
    source: https://gitlab.gnome.org/GNOME/gsound.git
    source-type: git
    plugin: autotools
    configflags: [--prefix=/snap/quadrapassel/current/usr, --disable-Werror]
    organize:
      snap/quadrapassel/current/usr: usr
    build-packages:
      - autoconf-archive
      - intltool
      - libgirepository1.0-dev
      - libglib2.0-dev
      - valac

  quadrapassel:
    after: [desktop-gnome-platform, gsound]
    source: .
    source-type: git
    plugin: meson
    # workaround the issue described in https://launchpad.net/bugs/1583250
    meson-parameters: [--prefix=/snap/quadrapassel/current/usr]
    organize:
      snap/quadrapassel/current/usr: usr
    override-build: |
      sed -i.bak -e 's|=org.gnome.Quadrapassel$|=${SNAP}/meta/gui/org.gnome.Quadrapassel.png|g' data/org.gnome.Quadrapassel.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/48x48/org.gnome.Quadrapassel.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/quadrapassel/current/usr/org.gnome.Quadrapassel.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - gettext
      - gsettings-desktop-schemas-dev
      - itstool
      - libcanberra-gtk3-dev
      - libclutter-1.0-dev
      - libclutter-gtk-1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - valac
